lang: "fr"
title: "UnitedCTF"
description: "Compétition informatique universitaire"

slack_url: https://united-ctf.slack.com
slack_inscription_url: https://join.slack.com/t/united-ctf/shared_invite/enQtNzMxNTU2NTk3NDA4LTQxMmRjYjkyZGRhMWI5MzU0NjJjNDgzODg5Zjg2ZDYyOWYwODQ3ZjRhOWEwNzA5MGM3OWE2MTc4ZWQ0OTE5MmQ
ctf:
  display: true
  registration_enabled: true
  place: "en ligne"
  name: "UnitedCTF 2020"
  url: "https://ctf.unitedctf.ca/"
  date_start: "18 septembre 18h30"
  date_end: "27 septembre 16h"

plugins:
  - "jekyll-seo-tag"
